from prefect import flow

@flow(log_prints=True)
def mastering_flow() -> str:
    print("Prefect flow is running")
"C:\Users\goku\Downloads\Hold it down (10).wav"
"C:\Users\goku\Downloads\newkilledsoftly.wav"
"C:\Users\goku\Downloads\Hot shit (4).wav"
"C:\Users\goku\Downloads\Newskie (2).wav"
"C:\Users\goku\Downloads\Hot shit (1).wav"
"C:\Users\goku\Downloads\Nipssey.wav"
"C:\Users\goku\Downloads\Nipssey  (2).wav"
"C:\Users\goku\Downloads\Stilll_KOTS.wav"
"C:\Users\goku\Downloads\Don't let me down  (10).wav"
"C:\Users\goku\Downloads\Fire (4).wav"
"C:\Users\goku\Downloads\FaceTime (15)_PREMASTER_-6dB.wav"
"C:\Users\goku\Downloads\Vegas - top teir (22).wav"
"C:\Users\goku\Downloads\Vegas - top teir (21).wav"
"C:\Users\goku\Downloads\FaceTime (15).wav"
"C:\Users\goku\Downloads\FaceTime (13).wav"
"C:\Users\goku\Downloads\FaceTime (6).wav"
"C:\Users\goku\Downloads\Vegas - Weeknd (3).wav"
"C:\Users\goku\Downloads\In the moment  (1).wav"
"C:\Users\goku\Downloads\DaddysGirls.wav"
"C:\Users\goku\Downloads\FM Vegas - Consistent (2).wav"
"C:\Users\goku\Downloads\Nipssey  (5).wav"
"C:\Users\goku\Downloads\Vegaas (3).wav"
"C:\Users\goku\Downloads\SOMEBODY (2).wav"
"C:\Users\goku\Downloads\SOMEBODY (1).wav"
"C:\Users\goku\Downloads\Got too (1).wav"
"C:\Users\goku\Downloads\I'm Him (13).wav"
"C:\Users\goku\Downloads\I'm Him (11).wav"
"C:\Users\goku\Downloads\enhanced_SLIDE N  EXTENDO (2).wav"
"C:\Users\goku\Downloads\Cleanthie (1).wav"
"C:\Users\goku\Downloads\Fall in Love (1).wav"
"C:\Users\goku\Downloads\FM Vegas - Consistent.wav"
"C:\Users\goku\Downloads\Walking_In_Rain.mp3"
"C:\Users\goku\Downloads\SB.wav"
"C:\Users\goku\Downloads\M.O (4).wav"
"C:\Users\goku\Downloads\I know.wav.asd"
"C:\Users\goku\Downloads\Mixdown(14).wav"
"C:\Users\goku\Downloads\Goku.wav"
"C:\Users\goku\Downloads\I don't give a fuck (1).wav"
"C:\Users\goku\Downloads\I know.wav"
"C:\Users\goku\Downloads\Vegas - Weeknd (1).wav"
"C:\Users\goku\Downloads\Hit you with the stick.wav"
"C:\Users\goku\Downloads\Jordon is the name.wav"
"C:\Users\goku\Downloads\(edit) Slidin.wav"
"C:\Users\goku\Downloads\Jordon_city.wav"
"C:\Users\goku\Downloads\killed softly.wav"
"C:\Users\goku\Downloads\Talk my shit.wav"
"C:\Users\goku\Downloads\SLIDE N  EXTENDO (7).wav"
"C:\Users\goku\Downloads\SLIDE_N_EXTENDO.wav"
"C:\Users\goku\Downloads\Needs master done.m4a"
"C:\Users\goku\Downloads\True.m4a"
